name: multiply-ui

channels:
  - conda-forge
  - defaults

dependencies:
  - bokeh =1.0.4
  - click =7.0
  - ipyleaflet = 0.10.4
  - ipywidgets =7.4.2
  - jupyterlab = 1.0
  - python =3.7.2
  - requests = 2.22
  - tornado =5.1.1
  - traitlets = 4.3.2
  - xarray =0.10.8
  # Testing
  - pytest
  - pytest-cov
  # For MULTIPLY platform
  - beautifulsoup4 = 4.6.0
  - gdal = 2.4
  - html5lib = 1.0.1
  - lxml = 4.3.2
  - numpy = 1.16
  - scipy = 1.2.1
  - shapely = 1.6.4
  - pyyaml = 3.12